### PR TITLE
Update conventions

### PR DESCRIPTION
**Pull request by Croydon**

### CODE REVIEW

**Comment by Croydon** [comment]
CI isn't enabled yet? 😄

**Comment by SSE4** [comment]
seems like no, I've just added it

**Comment by SSE4** [comment]
@Croydon build failed on CI, please take a look

**Comment by uilianries** [comment]
> [100%] Linking CXX executable bin/test_package
/usr/bin/ld: skipping incompatible /home/conan/.conan/data/muparser/2.2.6/conan/testing/package/7515fa2feb3aa2c5736d678a9ac2d907d9e6a9ad/lib/libmuparser.so when searching for -lmuparser
/usr/bin/ld: cannot find -lmuparser

**Comment by Croydon** [comment]
Woop. Thank you so much @SSE4 !

**Comment by danimtb** [comment]
Hi guys! Sorry to be late to the party 😄 CI was enable on my personal account; I started this some months ago but was not able to finish it. Thanks a lot for taking care and @SSE4 for the final fix!

**Pull request merged**
